// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2J3WigtmS-2JlcmVYizeEU16s_Ch-yr0',
    appId: '1:250021618534:web:d53af9d66fc1220c879ea7',
    messagingSenderId: '250021618534',
    projectId: 'webapp-8cdb1',
    authDomain: 'webapp-8cdb1.firebaseapp.com',
    databaseURL: 'https://webapp-8cdb1-default-rtdb.firebaseio.com',
    storageBucket: 'webapp-8cdb1.appspot.com',
    measurementId: 'G-RVBWX38XZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDECVzGWEi2BxoZJ32a6YQMq5sY7vMvFEI',
    appId: '1:250021618534:android:2cafbc50a45388ad879ea7',
    messagingSenderId: '250021618534',
    projectId: 'webapp-8cdb1',
    databaseURL: 'https://webapp-8cdb1-default-rtdb.firebaseio.com',
    storageBucket: 'webapp-8cdb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxSoRntgYnXsgBytMP_J0YLxm3zoXDtrA',
    appId: '1:250021618534:ios:708dac2da38e5e36879ea7',
    messagingSenderId: '250021618534',
    projectId: 'webapp-8cdb1',
    databaseURL: 'https://webapp-8cdb1-default-rtdb.firebaseio.com',
    storageBucket: 'webapp-8cdb1.appspot.com',
    iosBundleId: 'com.example.furnitureapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxSoRntgYnXsgBytMP_J0YLxm3zoXDtrA',
    appId: '1:250021618534:ios:c077602e2edce3f1879ea7',
    messagingSenderId: '250021618534',
    projectId: 'webapp-8cdb1',
    databaseURL: 'https://webapp-8cdb1-default-rtdb.firebaseio.com',
    storageBucket: 'webapp-8cdb1.appspot.com',
    iosBundleId: 'com.example.furnitureapp.RunnerTests',
  );
}
